#!/bin/bash

# script per dot command aufrufen für verzeichniswechsel und ENV zu ändern!
# . ./testscript.sh cd 1


#declare -A dirs
declare dirs

BOOKMARKS="$HOME/.config/tbm/bookmarks"

List ()
{
	#LoadBookmarks
	echo "Bookmarks:"
	for dir in "${!dirs[@]}"; do echo "$dir - ${dirs["$dir"]}"; done
	
}


AddDir () 
{
	#echo "adde $1"
	key="0"
	element_pos="unknown"
	if [ ! -z $2 ]; then
		#geht irgendwie nicht :(
		key=$2
	else
		for i in 0 9 8 7 6 5 4 3 2 1
		do
			element=${dirs[$i]}
			#echo "$i x${element}x"
			if [ -z $element ]; then
				#echo "$i existiert noch nicht: ${dirs[$i]}"
				key=$i
			fi 
			
			if [[ "${dirs[$i]}" == "$1" ]];then
				#echo "SET new ${dirs[$i]} to $1"
				element_pos="$i"
			fi
		done
	fi
	#echo $key $1 >> ~/.bookmarks
	#echo "add $1 als $key"
	if [[ "$element_pos" == "unknown" ]]; then
		dirs[$key]=$1
	else
		echo "Element already exist at: $element_pos" 
	fi
	#echo "test: ${dirs[$key]}"
	#echo bla $dirs
	SaveBookmarks
	
}

CD ()
{
	echo "change to $1"
	if [ -z ${dirs[$1]} ]; then
		echo "Entry $1 does not exist!"
	else
		cd ${dirs[$1]}
	fi
	#echo `pwd`
	
}

SetTerminalVariables ()
{
	TBM1=${dirs["1"]}
	TBM2=${dirs["2"]}
	TBM3=${dirs["3"]}
	TBM4=${dirs["4"]}
	TBM5=${dirs["5"]}
	TBM6=${dirs["6"]}
	TBM7=${dirs["7"]}
	TBM8=${dirs["8"]}
	TBM9=${dirs["9"]}
	TBM0=${dirs["0"]}
	
}
LoadBookmarks ()
{
	#echo "TTTEST"
	#f=`cat .bookmarks`
	#for line in ${f}; do echo "$line"; done
	if [ ! -f $BOOKMARKS ]; then
		touch $BOOKMARKS
	fi
	while read line; do
		key=`echo "$line"|awk '{print $1}'`
		path=`echo "$line"|awk '{print $2}'`
		#echo $key $path
		dirs[$key]=$path
	done < $BOOKMARKS
	
	SetTerminalVariables
}

SaveBookmarks()
{
	#echo "save"
	if [ -f $BOOKMARKS ]; then
		rm $BOOKMARKS
	fi
	touch $BOOKMARKS
	for dir in "${!dirs[@]}"; do echo "$dir ${dirs["$dir"]}" >> ${BOOKMARKS}; done
	SetTerminalVariables
}

RM ()
{
	if [[ "$1" == "all" ]];then
		unset dirs
	else
		unset dirs[$1]
	fi
	SaveBookmarks
	
}

Menu()
{
	List
	echo "Change dir to: "
	read input
	CD $input
}

RemoveFile()
{
	if [ -f $1 ]; then
		rm $1
	fi	
}
RemoveDir()
{
	if [ -d "$1" ]; then 
		if [ -L "$1" ]; then
			rm "$1"
		else
			rmdir "$1"
		fi
	fi	
}
Install()
{
	Uninstall
	
	mkdir "$HOME/.config/tbm/"
	DST="$HOME/.config/tbm/tbm"
	OUTPUT="$HOME/.bashrc"
	
	echo "Checking OS: `uname`"
	OS=`uname`
	
	if [[ "$OS" == "Darwin" ]]; then
		echo "I think this is a Mac. .bash_profile is used instead of .bashrc"
		OUTPUT="$HOME/.bash_profile"
	fi
	
	
	cp $OUTPUT ${OUTPUT}_tbm_save
	if [ ! -f $OUTPUT ]; then
		echo "Error: $OUTPUT does not exist"
	fi
	

	if [ `which realpath 2>/dev/null` ];then
		SRC=`realpath $0`
	else
		echo "The program 'realpath' does not exist. This is not fatal, unless you run 'tbm install' from ~/.config/tbm" 
		SRC=$0
	fi
	
	echo "Copy script from $SRC to $DST"
	if [[ "$SRC" != "$DST" ]];then
		#echo "COPY"
		cp $SRC $DST
		chmod +x $DST
	fi
	
	echo "Setup $OUTPUT"
	echo "#TBM_BEGIN">> $OUTPUT
	echo "#TBM_VERSION=0.2">>$OUTPUT
	#echo ". $DST nothing" >> $OUTPUT
	#echo "Set_TBM_Variables() {">> $OUTPUT
	#for i in 0 1 2 3 4 5 6 7 8 9 0; do
		#die for-schleife scheint langsam zu sein!
	#	echo "TBM${i}=\`$DST path ${i}\`;" >> $OUTPUT
	#done
	#echo "}" >> $OUTPUT
	for i in 0 1 2 3 4 5 6 7 8 9 0; do
		echo "tbm${i} () { echo \`$DST path ${i}\`; }" >> $OUTPUT
	done
	#echo "alias x='. $DST mark'" >> $OUTPUT
	echo "x () { . $DST add \$1;}" >> $OUTPUT
	#echo "alias c='. $DST cd'" >> $OUTPUT
	echo "#c () { . $DST cd \$1;}" >> $OUTPUT
	echo "c () { cd \`$DST path \$1\`; }" >> $OUTPUT
	echo "v () { $DST ls;}" >> $OUTPUT
	echo "tbm() { $DST \$1 \$2;}" >> $OUTPUT
	echo "#TBM_END">> $OUTPUT
	echo "Restart the terminal please!"
	
}

Uninstall()
{
	
	OUTPUT="$HOME/.bashrc"
	
	echo "Restore $OUTPUT"
	write="yes"
	while read -r line; do 
		if [[ "$line" == "#TBM_BEGIN" ]]; then
			write="no"
		fi
		if [[ "$write" == "yes" ]]; then
			l=$(echo "$line")
			echo $l >> ${HOME}/.bashrc_tbm_uninstall
		fi
		if [[ "$line" == "#TBM_END" ]]; then
			write="yes"
		fi	
	done < ${HOME}/.bashrc
	mv ${HOME}/.bashrc_tbm_uninstall ${HOME}/.bashrc
	
	RemoveFile ${HOME}/.bashrc_tbm_uninstall

	echo "Removing tbm and bookmarks"
	RemoveFile ${HOME}/.config/tbm/tbm
	RemoveFile ${HOME}/.config/tbm/bookmarks
	RemoveDir rmdir ${HOME}/.config/tbm

	echo "Done! Restart your terminal, please!"	
}

Help ()
{
	echo "TERMINAL BOOKMARKER"
	echo ""
	echo "Parameter [nr] are optional"
	echo "   add [nr]         - Add current directory to the bookmarks"
	echo "   ls               - List all bookmarks"
	echo "   cd [nr]          - Jump to bookmark"
	echo "   clear nr         - Delete a bookmark or all with 'clear all'"
	echo "   path nr          - Get the path as return"
	echo "   menu             - Shows the bookmark menu"
	echo "   install          - Install tbm in the .config directory and adds shortcuts"
	echo "   uninstall        - Remove tbm entirely"
	echo ""
	echo ""
	echo "The following features are only available after an installation"
	echo ""
	echo "Terminal shortcuts: "
	echo "   Just type the character (without tbm or anything else) in your terminal"
	echo "   x [nr]           - tbm add [nr]"
	echo "   c [nr]           - tbm cd [nr]"
	echo ""
	echo "Bash functions with access to the bookmarks: "
	echo "   tbm1,tmb2,....,tbm0 variables provide access to the bookmarked paths"
	echo "   For example: "
	echo "   ls \`tbm1\` -> list the directory stored in bookmark 1" 
}

#clear the dirs map and reload ist from file
unset dirs
LoadBookmarks
case $1 in
    add)
		if [ ! -z $2 ]; then
			name=$2
		fi
		dir=$PWD
        AddDir $dir $name
        List
        ;;
	ls)
		List
		;;
	path)
		echo ${dirs[$2]}
		;;
	clear)
		if [ -z $2 ]; then
			RM all
		else
			RM $2
		fi
		#List
		;;
	cd)
		if [ -z $2 ];then
			Menu
		else
			CD $2
		fi
		
		;;
	menu)
		Menu
		;;
	nothing)
	;;
	help)
		Help
		;;
	install)
		Install
		;;
	uninstall)
		Uninstall
		;;
    met*|meet*)
        ...
        ;;
    *)
		echo "Unknown command: $1"
		Help
		;;
        # You should have a default one too.
esac

unset dirs

